### ISSUE TITLE
Working Zones

### ISSUE THREAD

**Issue by Scurby** [lordkator/ZonamaDev#100]
The un-commented zones below can be loaded.
The commented zones are unknown status.

    --"09", 
	--"10",
	--"11",
	--"character_farm",
	--"cinco_city_test_m5",
	"corellia",
	--"creature_test",
	"dantooine",
	"dathomir",
	--"dungeon1",
	"endor",
	--"endor_asommers",
	--"floratest",
	--"godclient_test",
	"lok",
	"naboo",
	--"otoh_gunga",
	--"rivertest",
	"rori",
	--"runtimerules",
	--"simple",
	--"space_09",
	"space_corellia",
	"space_corellia_2",
	"space_dantooine",
	"space_dathomir",
	"space_endor",
	--"space_env",
	--"space_halos",
	--"space_heavy1",
	--"space_light1",
	"space_lok",
	"space_naboo",
	"space_naboo_2",
	"space_tatooine",
	"space_tatooine_2",
	"space_yavin4",
	--"taanab",
	"talus",
	"tatooine", -Required
	--"test_wearables",
	"tutorial", -Required
	--"umbra",
	--"watertabletest",
	"yavin4"

**Comment by karlbunch** [comment]
Hey @Scurby do we want to offer them to enable space? IMHO its just a trap at this point.. 

-k

**Comment by Scurby** [comment]
I would say not. Agreed.

**Comment by karlbunch** [comment]
Ok it's configurable here so can be changed later if needed:

https://github.com/lordkator/ZonamaDev/blob/master/server/emuyoda/yoda-config.lua.in

Closing for now.
