### ISSUE TITLE
Login to MySQL

### ISSUE THREAD

**Issue by ChazHS** [lordkator/ZonamaDev#105]
I am wanting to edit the database, but I can't find the root password documented anywhere. Please can you help?

**Comment by Scurby** [comment]
MySQL root pw = 12345678

**Comment by ChazHS** [comment]
Excellent, thanks. I also can't add myself as admin, what is the level required?

**Comment by Scurby** [comment]
https://github.com/lordkator/ZonamaDev/issues/71

**Comment by ChazHS** [comment]
Thanks
