### ISSUE TITLE
Do we want to make an "Agree to terms"

### ISSUE THREAD

**Issue by karlbunch** [lordkator/ZonamaDev#12]
Hey if you want to build a personal server have at it.. But here's how you get support.

Want to submit code, you're amazing here's how..

zenity --checkbox="Agree to terms"

**Comment by Scurby** [comment]
Yes, and a basic license.

**Comment by karlbunch** [comment]
Hey @Scurby can you get with the team and figure out the language here?

Also I'd like to make sure people agree that they will use proper IRC channels if they're doing private servers etc.

**Comment by Scurby** [comment]
This VM image is designed and built to enable development and testing of the SWGEmu Project. It is not designed to be used as a server. 

[What is SWGEmu](http://www.swgemu.com/forums/content.php?r=173)

We use [IRC](http://www.swgemu.com/forums/content.php?r=154-Configuring-mIRC) for communication. 

> irc.swgemu.com:6667  
>Please use the #opendev channel for development questions.

[Contributors License Agreement](http://review.swgemu.com/static/cla_individual.html)

**Comment by Farelli** [comment]
**This VM image is designed and built to enable development and testing of the SWGEmu Core3 Project. It is not designed to be used as a player server.**

[What is SWGEmu?](http://www.swgemu.com/forums/content.php?r=173)
[Development Documentation](http://www.swgemu.com/forums/showthread.php?t=120093)

We use [IRC](http://www.swgemu.com/forums/content.php?r=154-Configuring-mIRC) for communication.

>irc.swgemu.com:6667

> - Please use these channels:
> - #emuyoda for development environment questions (about ZonamaDev or EmuYoda)
> - #opendev for development questions.
> - #openqa for testing questions.
> - #swgemu for general chat.
> - #swgemuservers for community server issues.

The [Contributors License Agreement](http://review.swgemu.com/static/cla_individual.html) is required to submit code patches to Core3. Core3 is open-sourced under the [GNU AFFERO GENERAL PUBLIC LICENSE](http://review.swgemu.com/gitweb?p=Core3.git;a=blob;f=MMOCoreORB/COPYING;h=2def0e8831c25daae02b8b87cd439da27f1ac1c1;hb=refs/heads/unstable).

**Comment by karlbunch** [comment]
Feels like a yoda thing, moving to https://github.com/Zonama/emuyoda/projects/1
