### ISSUE TITLE
Trouble with Vagrant

### ISSUE THREAD

**Issue by nervousemu** [lordkator/ZonamaDev#126]
[Vagrant Issues.txt](https://github.com/lordkator/ZonamaDev/files/133135/Vagrant.Issues.txt)

I seem to be having issues with Vagrant and have been unable to figure out the issue. I have attached a notepad with the gitbash of what happens when I try to run the command.

Please let me know if you need any information from my end.

**Comment by karlbunch** [comment]
Something is wrong with your internet as far as I can tell see this part:

````
URL and error message are shown below:

URL: ["https://atlas.hashicorp.com/lordkator/swgemudev-deb-jessie"]
Error:

```

Can you navigate to that URL?

Please try the following in a git bash shell:

```bash
vagrant box remove lordkator/swgemudev-deb-jessie --all
```

Please provide the output of this command:

```bash
df -h $HOME
```

Please provide more details on your setup:

- What version of windows?
- Do you have a direct internet connection or are you using SOCKS proxy of any kind?
- Are you low on disk space in $HOME?

**Comment by nervousemu** [comment]
[$HOME output.txt](https://github.com/lordkator/ZonamaDev/files/133427/HOME.output.txt)
I have attached the output the the commands you gave me.

I have a direct internet connection and I am able to navigate to the URL that you gave me. I even created an account just to be sure.

I am running windows 7 64-bit with 45GB of hard drive space in my %HOME

**Comment by karlbunch** [comment]
Try this in gitbash shell:

```bash
vagrant global-status
```

If any instances show as active please remove them per the instructions given.

Then try:
```bash
rm -fr ~/ZonamaDev
curl -L http://downloads.lordkator.com/bootstrap.sh | bash
```

Let me know how that goes.  If we continue to fail this weekend we can meet in IRC and I'll work with you interactively.

**Comment by nervousemu** [comment]
I love you, that worked. I was able to get the virtual server built and I am able to follow through everything. Thank you so much!!

**Comment by karlbunch** [comment]
Did you find any misc vm's in the vagrant global-status command?  Or just removing and restarting seemed to work?

**Comment by karlbunch** [comment]
Ok @nervousemu I spent a couple hours this morning and was able to reproduce this issue on a vanilla Windows 10 install!

The issue seems to be related to the embedded copy of curl that vagrant includes, it depends on Microsoft C++ Runtime that isn't installed by default.

Download and run this:

https://www.microsoft.com/en-us/download/details.aspx?id=8328

then do:
```bash
curl -L http://downloads.lordkator.com/bootstrap.sh | bash -s destroy
````

**Comment by nervousemu** [comment]
When i ran the "vagrant global-status" command it did not show any other instances.

I still did the remove command and that seemed to clear up any obstruction i had. As i mentioned in the forum post i was able to get a virtual machine session going when i first started but i thought i screwed something up and went to delete everything and start again. I'm thinking that was where my issue was but i could be wrong.
