### ISSUE TITLE
Can we check VT enabled in bootstrap.sh and warn user?

### ISSUE THREAD

**Issue by karlbunch** [lordkator/ZonamaDev#128]
Is it possible we can warn the user before everything goes crazy on them?

Not sure how to find VT flags from command line in windows.

**Comment by cauwelsdev** [comment]
Microsoft® Hardware-Assisted Virtualization Detection Tool: https://www.microsoft.com/en-us/download/details.aspx?id=592
SystemInfo.exe will also output a Hyper-V section with a Yes or No for extensions, etc.
PowerShell Check for Virtualization: http://mikefrobbins.com/2012/09/06/use-powershell-to-check-for-processor-cpu-second-level-address-translation-slat-support/

**Comment by cauwelsdev** [comment]
SystemInfo.exe Hyper-V Section:

> Hyper-V Requirements:      VM Monitor Mode Extensions: Yes
>                            Virtualization Enabled In Firmware: Yes
>                            Second Level Address Translation: Yes
>                            Data Execution Prevention Available: Yes

**Comment by cauwelsdev** [comment]
Answer: `wmic cpu get VirtualizationFirmwareEnabled` returns TRUE if enabled or FALSE if disabled

**Comment by cauwelsdev** [comment]
it fails for me.

> $ ve=$(wmic cpu get VirtualizationFirmwareEnabled | sed -n 2p) echo $ve if["$ve" != "TRUE" ]
> TRUE if[TRUE                            != TRUE ]

seems $ve is adding in some spaces making it flag as false.

**Comment by cauwelsdev** [comment]
failing again.

```
$ curl -L http://downloads.lordkator.com/bootstrap.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  8661  100  8661    0     0  10447      0 --:--:-- --:--:-- --:--:-- 8458k
** Checking for Git Bash **
** BASH_VERSION: 4.3.42(5)-release **
** Checking for VirtualBox **
Virtualization Enabled: TRUE
############################################################################
## ERROR: YOU MUST ENABLE VIRTUALIZATION IN YOUR BIOS BEFORE YOU CONTINUE ##
############################################################################

** Please close this window, boot into your BIOS, enable virtualization and try again **
```

**Comment by karlbunch** [comment]
FAIL meed to fix

**Comment by karlbunch** [comment]
Fails on a i7-2600k because it only supports vt-x

Maybe we need to do a check for: SecondLevelAddressTranslationExtensions

Making the error a prompt instead for now.

**Comment by cauwelsdev** [comment]
That could work, also check for: VMMonitorModeExtensions
Maybe run all 3 as a check, and if any of the three return true then VM is enabled and allow bootstrap.sh to continue?

**Comment by karlbunch** [comment]
Prompt seems to work, wish this was easier to do for real.
