### ISSUE TITLE
Make zone/planet selection a bit easier

### ISSUE THREAD

**Issue by karlbunch** [lordkator/ZonamaDev#130]
It's a bit clunky right now, should have a select-all and should select when you click anywhere in the cell.. not to mention running off the page is sucky.. maybe even use a different ui element.

**Comment by cauwelsdev** [comment]
Might be worth adding in an option to change the zones later on in Yoda, just in case a person disabled Zone X because they were testing only Zone Y but Zone X is now relevant to their testing purposes or a new Zone is added.

**Comment by karlbunch** [comment]
Yea I was planning on putting a 'edit' icon in the box with zones and allow people to change.

Also would like to add [Select All] and make the table cells work to select also etc.

**Comment by karlbunch** [comment]
Moved to https://github.com/Zonama/emuyoda/projects/1
