### ISSUE TITLE
Setup script for linux host?

### ISSUE THREAD

**Issue by bluefalcon13** [lordkator/ZonamaDev#135]
I generally leave my laptop logged into linux (Debian Testing) as it is my dev environment for my C++ class.  It seems the setup script always fails.
[setup-script-error.txt](https://github.com/lordkator/ZonamaDev/files/136682/setup-script-error.txt)

is there a chance this issue can be resolved?  I would much prefer to stay in linux.  Currently I am going to start looking up how to use either a) a custom built vm for dev setup, or b) just using the host OS (I would prefer a VM, as keeping school and other separate would be preferred).

**Comment by karlbunch** [comment]
Oh this is cool if you want we can work together on it, I haven't tried to make it work on Linux yet, a couple of issues out of the box will be you need a new version of vargant (1.8.1) not the one in most distros as its way out of date.  

I'd be happy to try and work through it with you.. Help me a bit with what version of Linux including Kernel versions etc and have you downloaded the latest virtualbox?

Also what does this return?: vagrant --version

**Comment by bluefalcon13** [comment]
sure, so I am running a Debian-Testing build, therefore it is usually lacking some tools (IE, vagrant was not in the default install, just did an apt-get for it).

Kernel: 4.3.0-1-amd64
vagrant: 1.8.1
virtualbox: 5.0.14_Debianr105127

everything is up to date, just let me know what you need me to try

**Comment by karlbunch** [comment]
OK in the morning I'll push a couple quick changes to support linux but I won't have time to test until the weekend, if you're interested it would be nice to see you run the test etc. I'll give instructions about lets say 6am Eastern Time US.

Also I'll be in #emuyoda in IRC if you want to connect this weekend.

**Comment by bluefalcon13** [comment]
Sounds good, I get out of lab at about 0930 MST and can give it a whirl after that.

**Comment by karlbunch** [comment]
Sounds good, I am digging around a bit it appears the culprit might be here:

```bash
zlib is missing; necessary for building libxml2
```

You are most likely missing the zlib-dev package on Jessie this is: zlib1g-dev

**Comment by karlbunch** [comment]
Make sure you have hardware virtualization enabled in your BIOS!

I would suggest install zlib-dev and then try this:

```bash
curl -L http://downloads.lordkator.com/bootstrap.sh | bash -s destroy
```

It will try and cleanup everything and re-run the setup.

If it fails please share the output.

**Comment by bluefalcon13** [comment]
zlib-dev: doh, completely missed that in the log.  installed it via apt-get

virtualization is definitely enabled, I play with VMs regularly.

re-ran the script after install zlib-dev, and it errors out on this part after the reset:

######################################
## ZonamaDev Host Environment Reset ##
######################################
** Checking for VirtualBox **
bash: line 207: /usr/bin/VBoxManage/VBoxManage: Not a directory
Unsupported version of virtualbox (), please upgrade to 5.0.12 or higher

took a look in the /usr/bin folder, here is what I have for VBoxManage:

jfisher@precision-m4500:/usr/bin$ ls -l | grep VBoxManage
lrwxrwxrwx 1 root root          27 Feb  4 13:21 VBoxManage -> ../share/virtualbox/VBox.sh

so a link is in /usr/bin/ not a subdirectory, but the link itself.

**Comment by bluefalcon13** [comment]
ahh I see it, line 207, since the var ({vbm}) calls the actual VBoxManage itself, and you have VBoxManage being called like this:

{vbm}\VBoxManage --version

when expanded looks like:
/usr/bin/VBoxManage/VBoxManage

should just be:
{vbm} --version

**Comment by bluefalcon13** [comment]
So I am completely nub-level with github, as I have never used it.  Just as an FYI, I have performed the 'hard way' via cli, and it is working fully.  I also forked your main branch so I can attempt to fix and run the easy way.

**Comment by bluefalcon13** [comment]
Alright, I just figured it out.  I put in a pull request with the fix.  I have tested it on my machine, and the bootstrap works wonderfully!

**Comment by karlbunch** [comment]
That's awesome I will review tonight or tomorrow, thank you so much for the help!
