### ISSUE TITLE
And now what?

### ISSUE THREAD

**Issue by 42yen** [lordkator/ZonamaDev#159]
I followed the instructions here for Windows host:
https://github.com/lordkator/ZonamaDev

Downloaded the programs, installed, rebooted and then launched Git and ran bootstrap. There were no errors and everything loaded in fine (from what I could tell).

How do I launch the server now?

**Comment by 42yen** [comment]
![destroy and start fresh](https://cloud.githubusercontent.com/assets/19244141/15094932/6d22ef0a-1470-11e6-9f53-d730695d967a.jpg)

**Comment by 42yen** [comment]
^ Nuked the previous install in case I somehow mucked it up.

**Comment by 42yen** [comment]
![reinstall progress](https://cloud.githubusercontent.com/assets/19244141/15094937/849d123c-1470-11e6-9316-c51953c6e8f7.jpg)

**Comment by 42yen** [comment]
^ current progress of install

**Comment by 42yen** [comment]
![trans closed](https://cloud.githubusercontent.com/assets/19244141/15094969/97e89482-1471-11e6-845c-2d5925b329d3.jpg)

**Comment by 42yen** [comment]
^ transmission closed (error)

**Comment by 42yen** [comment]
![resumed dl](https://cloud.githubusercontent.com/assets/19244141/15094973/a6202c9a-1471-11e6-9d52-b7c4b28a93e9.jpg)

**Comment by 42yen** [comment]
^ resumed dl

**Comment by 42yen** [comment]
![finished](https://cloud.githubusercontent.com/assets/19244141/15095012/e9b9cf3c-1472-11e6-987c-c5af4fbc3f41.jpg)

**Comment by 42yen** [comment]
download complete, but now... what is the next step? Tutorial says to follow instructions, but I am not seeing any. =(

**Comment by karlbunch** [comment]
I take it you managed to get the setup to complete?

**Comment by 42yen** [comment]
Aye, was a bit more "hurry up 'n wait" than I thought it would be, but as the old saying goes "patience grasshopper... patience".

=)
