### ISSUE TITLE
Add option to link forums accounts to game DB.

### ISSUE THREAD

**Issue by Mesagoppinmypants** [lordkator/ZonamaDev#160]

**Comment by karlbunch** [comment]
Can you give more details? Forums accounts where? and which game db?

**Comment by Mesagoppinmypants** [comment]
As of right now, when you disable auto-registration you will manually have to make accounts in the game's DB in order to play. But lots of people have their own forums that uses a MySQL DB to hold forum account info. Would it be possible so forums like myBB and Xenforo forum accounts connect to the accounts table in the game database when auto-registration is off?

**Comment by karlbunch** [comment]
Technically it's possible to use the Yoda API to do this now, it's just not well documented.

**Comment by Mesagoppinmypants** [comment]
Yeah it would be helpful if there were instructions in the emuyoda UI. Also possibly an xml output for the server status.

**Comment by karlbunch** [comment]
The xml status is a Core3 service not a Yoda service.

curl 'http://127.0.0.1:44455/'

**Comment by Mesagoppinmypants** [comment]
@karlbunch Would you mind explaining how we can connect a MySQL forum database to the game MySQL so the accounts are linked?

**Comment by Mesagoppinmypants** [comment]
@karlbunch I imagine it might be difficult since both the forums and game use a different encryption.

**Comment by karlbunch** [comment]
Some quick notes on how this might be done:

https://github.com/lordkator/ZonamaDev/wiki/Create-users-via-EmuYoda-API
