### ISSUE TITLE
Unable to make an admin toon

### ISSUE THREAD

**Issue by QuiteDrunkOnGin** [lordkator/ZonamaDev#162]
[ClientGame]
0fd345d9 = true
[ClientUserInterface]
debugExamine=1

.include "swgemu_login.cfg"
.include "swgemu_live.cfg"
.include "swgemu_preload.cfg"
.include "options.cfg"
.include "user.cfg"

C+P of my user.cfg and swemu.cfg went back out to windows but none of the characters i make have godmode enabled. The account is listed as admin lvl 15 in mysql tryed rebuilding restarting to no avail.

**Comment by karlbunch** [comment]
Are you using the SWG Emu launcher to run the game?

Also do you have any mods loaded on the client side?

Are you certain you're editing the files in the correct directory?

**Comment by karlbunch** [comment]
Closing no feedback and looks like from IRC you've got it workin.

**Comment by QuiteDrunkOnGin** [comment]
Hey apologies it took me so long to respond i saw the issue got closed and it was working but intermittently. The issue was that if you alt tab out during character creation that toon will not have admin rights.
 

Sent from Yahoo Mail. Get the app 

    On Thursday, 2 June 2016, 10:04, Karl Bunch <notifications@github.com> wrote:
 

 Are you using the SWG Emu launcher to run the game?Also do you have any mods loaded on the client side?Are you certain you're editing the files in the correct directory?—
