### ISSUE TITLE
Can't run the setup, keep getting this error

### ISSUE THREAD

**Issue by cdnghost** [lordkator/ZonamaDev#167]
So I download all three of the programs as indicated and installed them, I set up a windows 8.1 VM as well not sure if I need to.. anyway I am running Windows 10 pro latest build.
I open up the gitbash as instructed and enter the line of code for fast setup and get the following.  Please help thanks.

** Checking for Git Bash **
** BASH_VERSION: 4.3.42(5)-release **
** Checking for VirtualBox **
** Virtualbox version 5.0.20r106931 **
** Checking for Vagrant **
** Vagrant version 1.8.3 **
** ZDHOME=/c/Users/Nate **
Cloning into 'ZonamaDev'...
remote: Counting objects: 4504, done.
remote: Total 4504 (delta 0), reused 0 (delta 0), pack-reused 4503
Receiving objects: 100% (4504/4504), 16.38 MiB | 3.66 MiB/s, done.
Resolving deltas: 100% (2693/2693), done.
Checking connectivity... done.
Checking out files: 100% (576/576), done.
** Running in /c/Users/Nate/ZonamaDev/fasttrack **
** Setting config.yml to use 8 cores for guest and 6144m of ram. **
vagrant up
Installing the 'vagrant-vbguest' plugin. This can take a few minutes...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

Checksum of /versions does not match the checksum provided by server! Something is wrong.

Warning: this Gemfile contains multiple primary sources. Using `source` more than once without a block is a security risk, and may result in installing unexpected gems. To resolve this warning, use a block to indicate which gems should come from the secondary source. To upgrade this warning to an error, run `bundle config disable_multisource true`.
Installing the 'vagrant-reload' plugin. This can take a few minutes...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

Checksum of /versions does not match the checksum provided by server! Something is wrong.

Warning: this Gemfile contains multiple primary sources. Using `source` more than once without a block is a security risk, and may result in installing unexpected gems. To resolve this warning, use a block to indicate which gems should come from the secondary source. To upgrade this warning to an error, run `bundle config disable_multisource true`.
Installing the 'vagrant-triggers' plugin. This can take a few minutes...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

Checksum of /versions does not match the checksum provided by server! Something is wrong.

Warning: this Gemfile contains multiple primary sources. Using `source` more than once without a block is a security risk, and may result in installing unexpected gems. To resolve this warning, use a block to indicate which gems should come from the secondary source. To upgrade this warning to an error, run `bundle config disable_multisource true`.
Some plugins had to be installed, please re-run your command

real    0m28.929s
user    0m0.000s
sys     0m0.016s
** Running vagrant up again after plugin install **
Installing the 'vagrant-vbguest' plugin. This can take a few minutes...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

Checksum of /versions does not match the checksum provided by server! Something is wrong.

Warning: this Gemfile contains multiple primary sources. Using `source` more than once without a block is a security risk, and may result in installing unexpected gems. To resolve this warning, use a block to indicate which gems should come from the secondary source. To upgrade this warning to an error, run `bundle config disable_multisource true`.
Installing the 'vagrant-reload' plugin. This can take a few minutes...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

Checksum of /versions does not match the checksum provided by server! Something is wrong.

Warning: this Gemfile contains multiple primary sources. Using `source` more than once without a block is a security risk, and may result in installing unexpected gems. To resolve this warning, use a block to indicate which gems should come from the secondary source. To upgrade this warning to an error, run `bundle config disable_multisource true`.
Installing the 'vagrant-triggers' plugin. This can take a few minutes...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

Checksum of /versions does not match the checksum provided by server! Something is wrong.

Warning: this Gemfile contains multiple primary sources. Using `source` more than once without a block is a security risk, and may result in installing unexpected gems. To resolve this warning, use a block to indicate which gems should come from the secondary source. To upgrade this warning to an error, run `bundle config disable_multisource true`.
Some plugins had to be installed, please re-run your command

real    0m30.474s
user    0m0.000s
sys     0m0.000s
** Vagrant failed to bring the VM image up, look at errors above for clues **

**Comment by karlbunch** [comment]
Seems like you are either behind a firewall or have issues connecting to the gem server.

Please try again and re-open this issue if your problem continues.

You can also try a fresh re-install by opening a git bash window and typing:

```bash
curl -L http://downloads.lordkator.com/bootstrap.sh | bash -s uninstall
```

Reboot your computer and try starting from the beginning.

**Comment by cdnghost** [comment]
I have done the reinstall a few times and no luck prior to posting.  My set up is as follows

2009 Mac Pro running Windows 10 pro in boot camp, have installed all the required software as per install instructions.

My network is not running any firewalls, but may have some ports closed.... Are there any specific ports that should be opened? The network is running on a apple extreme router which Is connected to my ISP router....

**Comment by karlbunch** [comment]
If you're on a mac don't bother with boot camp.

Open a terminal in osx and run the bootstrap.

**Comment by cdnghost** [comment]
But then how would I play if I build the server on the mac side?  All the emulators blow for running Windows....

**Comment by karlbunch** [comment]
I use Win on OSX with SWGEmu client, works very well and is quite stable.

That said I run my test server on a mac-mini under OSX so it can stay up all the time etc.

I'm at a loss as to what's going on with your ruby setup.  I'm assuming all you did was install the required pre-reqs on a vanilla win10 install?

I might suggest you uninstall Vagrant, reboot and try again.

**Comment by karlbunch** [comment]
http://wineskin.urgesoftware.com/

**Comment by cdnghost** [comment]
I will try both! Thanks!!

**Comment by cdnghost** [comment]
I'll let you know how it all goes

**Comment by karlbunch** [comment]
Also I'm hanging out in #emuyoda in IRC if you want get a bit more interactive help.

**Comment by cdnghost** [comment]
haven't been able to do any work today... will test this out in the next day or 2...

Thanks!

**Comment by cdnghost** [comment]
Looks like I have a server built now, but am having issues with wineskin getting the SWGemu etc to install.... do you know where I can find a walk-through? keeps on crashing for me....

**Comment by karlbunch** [comment]
If you have it working in Bootcamp you can just use that copy, don't bother doing install.

Tell wineskin to make a container and then in the container just copy everything from /Volumes/BOOTCAMP/SwgEmu/ into {path to app}/drive_c/

**Comment by cdnghost** [comment]
last question what wrapper do i use i used the latest 1.9.11 i think but get no mouse support..... which is odd

**Comment by karlbunch** [comment]
If you PM me in IRC I can walk you through it...
