### ISSUE TITLE
Consider a cloud based base box build

### ISSUE THREAD

**Issue by karlbunch** [lordkator/ZonamaDev#17]
http://chef.github.io/bento/

https://wiki.debian.org/Teams/Cloud/RebuildVagrantBaseBoxes

**Comment by Scurby** [comment]
http://jenkins-ci.org/content/official-jenkins-lts-docker-image

**Comment by karlbunch** [comment]
Yea I meant the base box build as in making the base box somewhere instead of on our own machines.

**Comment by karlbunch** [comment]
Base box builds don't happen often enough to bother.
