### ISSUE TITLE
Having Trouble Creating An Admin Character

### ISSUE THREAD

**Issue by Vorns** [lordkator/ZonamaDev#170]
I'm having trouble creating an Admin character on my setup.
I know I've set things up correctly but it's not working.

user.cfg file contents are:
[ClientGame]
ofd345d9 = true

[SwgClient]
allowMultipleInstances = true

[ClientUserInterFace]
debugExamine = 1

swgemu.cfg:
.include "swgemu_login.cfg"
.include "swgemu_live.cfg"
.include "swgemu_preload.cfg"
.include "options.cfg"
.include "user.cfg"

I went into MySql and changed the account from 0 to 15. I have two different accounts setup one for admin and the other as a regular play. I've changed both from player to admin and back and neither will make an admin character. Not sure what I'm doing wrong. Can anyone help?

**Comment by Joeyarrabi** [comment]
I'm having a similar problem.  However, I noticed that in your user.cfg it looks like you put an o (letter o) rather than a 0 (number 0) at -

[ClientGame]
ofd345d9 = true

It should be -

[ClientGame]
0fd345d9 = true

**Comment by Vorns** [comment]
@Joeyarrabi Wow, thanks for pointing that one out. It would have taken me another month to figure out that I did that :D 
The weird thing is, is that I set up this environment once before and admin worked, and I've never changed the config files after I edited them the first time.

**Comment by smarcotte4g** [comment]
@Vorns Did you use the username that SWGEmu Yoda says to use? Or did you create a new account and change the admin_level in the database to 15? The username that I am being told to use has an admin level of 15 but my character does not have permissions.

**Comment by Vorns** [comment]
I used the account that I first created when I started SWGEMU Yoda when that didn't work I made and new account and changed it to 15 and I corrected the user.cfg. Still not working.

**Comment by cdnghost** [comment]
I am in the same boat, finally got my server up and running! 
Made my admin account as it shows under the Server information tab

Account; admin_level 15 

it is the account i used to log on, and create now 3 toons and none of them have had any admin rights....
I have the user.cfg and swgemu.cfg updated but nothing works yet... very frustrating

**Comment by Vorns** [comment]
Core3[2882]>> (37 s) [TreeArchive] ERROR - Did not find fileName: godclient_cylinder_30.apt

Does anyone know where this file is located?
Has it been removed?

**Comment by karlbunch** [comment]
Hey it seem there might have been a push that changed Admin behavior, I'm digging in but for now I don't know of a work around, please stand by.

**Comment by Joeyarrabi** [comment]
I'm looking through [this](http://review.swgemu.com/#/c/4616/) right now.  Has a lot of changes in the way account info is fetched.  (At least it appears that way, I am no expert)

**Comment by karlbunch** [comment]
Nahh that's too far back, whatever happened has been in the last 7 days.

**Comment by karlbunch** [comment]
Ok this was a Core3 code issue not a ZD issue but we worked it out.

Until this patch goes mainline you can do this to work around it, open a terminal in ZD and type:

```bash
rm ~/workspace/Core3/MMOCoreORB/build/unix/config.log
cd ~/workspace/Core3/MMOCoreORB
git fetch http://review.swgemu.com/Core3 refs/changes/38/4938/2 && git cherry-pick FETCH_HEAD
swgemu stop && swgemu build && swgemu start
```

Then you should be able to login as the first account you created as the admin when Emu Yoda asked you to create one.  Any existing toon will be broken, you'll need to create a new one.

Or best bet would be to destroy and restart and then type the above commands.

Most likely the patch will make it to latest in a couple days and these steps will not be required.

**All this said any toons created while this bug existed are not admin and you will need to create a new toon to get admin abilities and then use: /setgodmode toonName admin to fix**

**Comment by cdnghost** [comment]
Thanks Karl, in the midst of rebuilding a new server... round 9 or 10 lol.... just a question.. the user.cfg and swgemu.cfg files... 
here C:\Program Files (x86)\StarWarsGalaxies\SWGEmu\
or should they be in with the launcher C:\Program Files (x86)\SWGEmu\SWGEmu Launchpad
just curious... could be this workaround will fix it but just wanted to be sure

Thanks

**Comment by Joeyarrabi** [comment]
Thanks Karl, got everything working just fine!

**Comment by karlbunch** [comment]
I just confirmed, if you start from scratch the patch will fix admin issues.

Remember, slow is fast, fast is slow, follow directions, make sure your Yoda user/pw is what you use in the client when you login.

I highly recommend destroying your ZD and re-building so that any orphaned characters don't confuse you or others later.

**Comment by Vorns** [comment]
@karlbunch Thank you!

**Comment by Degrath** [comment]
Has this been corrected in recent builds? Yesterday I did a fresh install and admin account characters were all god mode. This evening I did another fresh install and now Admin account with admin level 15 characters will not go into god mode and have no permissions. the Client is all set right and it was working fine yesterday.

**Comment by karlbunch** [comment]
Yes it's closed from a ZD perspective.
