### ISSUE TITLE
Not sure if this is an issue but I can't for the life of me enable any jedi almost no fs skills are trainable

### ISSUE THREAD

**Issue by cdnghost** [lordkator/ZonamaDev#173]
Hey so thanks for the patch to allow admin commands!

Now that that is working I have tried and failed numerous times to enable a Jedi toon.
I can add the force sensitive command and the novice fs boxes but that's it.  Not one Jedi skill works and none of the shrines allow me to meditate even though the option is there and my toon is kneeling.

I have tried /resetJedi and started again only to not have any of the skills stick at all.. all other profs work perfectly.

I can enable the old skills via /grantSkill jedi_padawan_master etc but it consumes skill points and the skills can not be surrender I have to delete the toon and try again.

Am I missing something or is jedi just not doable using this server setup?

thanks

p.s. if this is not the area to be posting this please let me know

**Comment by cdnghost** [comment]
Ignore me figured it out

**Comment by karakias** [comment]
Well maybe you can help me sir, as I have ran into the same problem, been racking my brain, but no luck. Any help or info would be appreciated.

**Comment by cdnghost** [comment]
I followed this guide, to just have Jedi work follow step 1 and rebuild..... worked for me

http://www.modthegalaxy.com/forums/thread-creating-pre-pub-9-style-or-choice-jedi
