### ISSUE TITLE
05git-config command not found?

### ISSUE THREAD

**Issue by bb-customs** [lordkator/ZonamaDev#175]
hey lordkator, i work and learn modding SWG an i want to learn on my own server, i have problems with complieting the devsetup, the terminal in GUI hang on 05git-config with message command not found, i think thats the main problem to finish the SWGEmu Yoda setting or?

another question .... must i create the workspace data with the core3? at home/vagrant/  or is thin only for VM ?

greets Amrok

**Comment by karlbunch** [comment]
If you want to make a standalone server, you're on you own!

That said here's a wiki that I've been keeping as people share challenges they've had:

https://github.com/lordkator/ZonamaDev/wiki/Standalone-Server-Notes
