### ISSUE TITLE
Installing ZonamaDev VM on OVH Linux host

### ISSUE THREAD

**Issue by c0pp3r** [lordkator/ZonamaDev#176]
Hello,
I am attempting to setup vagrant/virtualbox with the ZonamaDev VM on a cloud host. I am getting the following error when attempting to run the start script after running all the prerequisites 

There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.
 
Command: ["startvm", "6d054a10-e7bf-47aa-a123-e9418116e5f0", "--type", "gui"]
 
Stderr: VBoxManage: error: This VM was configured to use 3D acceleration. However, the 3D support of the host is not working properly and the VM cannot be started. To fix this problem, either fix the host 3D support (update the host graphics driver?) or disable 3D acceleration in the VM settings (VERR_NOT_AVAILABLE)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component ConsoleWrap, interface IConsole

I am attempting this from a vnc session with XFCE as the gui.

**Comment by c0pp3r** [comment]
Found a work around. If you run the VM with VBoxHeadless -v on you can then RDP into the VM to complete the gui setup.

For OVH I used ssh to tunnel out 3389 to RDP without exposing this to the internet. Might be worth looking into adding a headless option into the setup to allow for this type of setup. Pretty happy with the testing setup I have, can have multiple ZD VMs hosted in the cloud this way.

**Comment by karlbunch** [comment]
For stanalone servers please see:

https://github.com/lordkator/ZonamaDev/wiki/Standalone-Server-Notes

**Comment by c0pp3r** [comment]
Hey Karl,

This wasn't a stand-alone server install. The goal was to take a cloud server and have it run the ZD VM. This way the server could be left to run other things but have VirtualBox and a VM via ZD.
