### ISSUE TITLE
Vagrant can't handle Windows user names with special characters

### ISSUE THREAD

**Issue by Loshult** [lordkator/ZonamaDev#179]
The following error appears if you have a user name in Windows with special characters. In this case Åkerblom.

vagrant up
C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/fileutils.rb:252:in `mkdir': Invalid argument @ dir_s_mkdir - C:/Users/?kerblom (Errno::EINVAL)
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/fileutils.rb:252:in`fu_mkdir'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/fileutils.rb:226:in `block (2 levels) in mkdir_p'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/fileutils.rb:224:in`reverse_each'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/fileutils.rb:224:in `block in mkdir_p'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/fileutils.rb:210:in`each'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/fileutils.rb:210:in `mkdir_p'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/environment.rb:777:in`block in setup_home_path'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/environment.rb:772:in `each'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/environment.rb:772:in`setup_home_path'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/environment.rb:129:in `initialize'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.6/bin/vagrant:165:in`new'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.6/bin/vagrant:165:in `<main>'

real    0m1.384s
user    0m0.000s
sys     0m0.016s
*\* Vagrant failed to bring the VM image up, look at errors above for clues **
*\* If this continues get help here: https://github.com/lordkator/ZonamaDev/issues **

**Comment by Loshult** [comment]
I solved it by setting the environment variable VAGRANT_HOME to a path without any special characters. Guess the script could do that.

**Comment by karlbunch** [comment]
Sadly this is a windows Ruby issue, not sure what the best solution is, I'm open to ideas.

**Comment by Loshult** [comment]
If you can detect it you could ask the user to set the VAGRANT_HOME environment variable to a path without special characters.

**Comment by karlbunch** [comment]
Pull request welcome but I don't have an easy way to test this idea.
