### ISSUE TITLE
Issue with Git after trying to re-install

### ISSUE THREAD

**Issue by chromulus** [lordkator/ZonamaDev#182]
Hi, I have been having endless issues for the last few days, I have posted on the swgemu forums site but am tring here just incase, if I'm in the wrong place I do apologise,, my origin post was:

Hi n thanks for all the hard work, I got testserver up n running for about a week and now i keep getting the following error on booting up server

Core3[2622]>> Program received signal SIGBUS, Bus error.
Core3[2622]>> 0x00007ffff6fd5048 in ?? () from /usr/lib/x86_64-linux-gnu/libdb-5.3.so
Core3[2622]>> (gdb) 

I was playin on the server when it lost signal with host and it was after shutting down n rebooting that the problem first started, i have searched everywhere to try find a solution but it seems to be a bit above my level to sort out.

any suggestions would be greatly appreciated as i cant figure out what Ive broken, tnx

EDIT: out of frustration I uninstalled and re-installed everything, deleting any folders left after install and any evidence of the install, ran the uninstall command though git, then tried re-installing everything and now I keep getting the following in Git during setup

Stderr: VBoxManage.exe: error: Could not launch a process for the machine 'ZonamaDev-1475736736' (VERR_UNRESOLVED_ERROR)
VBoxManage.exe: error: Details: code VBOX_E_IPRT_ERROR (0x80bb0005), component MachineWrap, interface IMachine, callee IUnknown
VBoxManage.exe: error: Context: "LaunchVMProcess(a->session, sessionType.raw(), env.raw(), progress.asOutParam())" at line 589 of file VBoxManageMisc.cpp

real    0m19.245s
user    0m0.015s
sys     0m0.000s
** Vagrant failed to bring the VM image up, look at errors above for clues **
** If this continues get help here: [url]https://github.com/lordkator/ZonamaDev/issues[/url] **

As before Ive tried looking everywhere but cant seem to find out whats causing the problem or how to resolve it but would love to now know what I actually managed to break and how so I can stay clear in the future, any advice will still be greatly appreciated  :)

**Comment by Farelli** [comment]
I have some questions:

- "I got testserver up n running for about a week and now i keep getting the following error on booting up server"  -- Something changed then. What did you do?

- "out of frustration I uninstalled and re-installed everything" -- You listed some things you did, but I notice you didn't mention what it says in ReadMe.md:

```
Advanced Featues

DESTROY AND START FRESH

To uninstall and re-install fresh on the host system type:

curl -L http://downloads.lordkator.com/bootstrap.sh | bash -s destroy
```

This means not in your ZonamaDev environment, but the machine running VirtualBox. I assume you're using Windows, so you need to open git bash and enter that line.

That will destroy your current ZD environment and create a new one from scratch. That will be the easiest way to fix your problems if everything was working before.
