### ISSUE TITLE
wxLua support for World Spawner Tool

### ISSUE THREAD

**Issue by Scurby** [lordkator/ZonamaDev#186]
Add option to install wxWidgets and wxLua in support of World Spawner Tool
[http://wxlua.sourceforge.net/](http://wxlua.sourceforge.net/)
[http://wxlua.sourceforge.net/docs/install.html](http://wxlua.sourceforge.net/docs/install.html)

**Comment by karlbunch** [comment]
Moved to https://github.com/Zonama/ZonamaDev/projects/2
