### ISSUE TITLE
Vagrant failed to bring up VM Image

### ISSUE THREAD

**Issue by TrueLokitus** [lordkator/ZonamaDev#187]
So, I've gone through the first two; git clone https://github.com/lordkator/ZonamaDev.git
cd ZonamaDev/fasttrack

Then as I type in ./setup.sh
it runs up to a point 
$ ./setup.sh
*\* Using default cores/ram **
vagrant up
C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/fileutils.rb:1444:in `rmdir': Directory not empty @ dir_s_rmdir - C:/Users/RCGre/AppData/Local/Temp/vagrant-fs-case-sensitive20161026-11220-i4sdr5 (Errno::ENOTEMPTY)
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/fileutils.rb:1444:in`block in remove_dir1'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/fileutils.rb:1458:in `platform_support'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/fileutils.rb:1443:in`remove_dir1'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/fileutils.rb:1436:in `remove'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/fileutils.rb:778:in`block in remove_entry'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/fileutils.rb:1493:in `ensure in postorder_traverse'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/fileutils.rb:1493:in`postorder_traverse'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/fileutils.rb:776:in `remove_entry'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/tmpdir.rb:94:in`mktmpdir'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/util/platform.rb:139:in `fs_case_sensitive?'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/util/platform.rb:157:in`fs_real_path'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/environment.rb:121:in `initialize'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.6/bin/vagrant:165:in`new'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.6/bin/vagrant:165:in `<main>'
C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/fileutils.rb:1444:in`rmdir': Directory not empty @ dir_s_rmdir - C:/Users/RCGre/AppData/Local/Temp/vagrant-fs-case-sensitive20161026-7124-11c78l8 (Errno::ENOTEMPTY)
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/fileutils.rb:1444:in `block in remove_dir1'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/fileutils.rb:1458:in`platform_support'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/fileutils.rb:1443:in `remove_dir1'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/fileutils.rb:1436:in`remove'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/fileutils.rb:778:in `block in remove_entry'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/fileutils.rb:1493:in`ensure in postorder_traverse'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/fileutils.rb:1493:in `postorder_traverse'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/fileutils.rb:776:in`remove_entry'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/tmpdir.rb:94:in `mktmpdir'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/util/platform.rb:139:in`fs_case_sensitive?'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/util/platform.rb:157:in `fs_real_path'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/environment.rb:121:in`initialize'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.6/bin/vagrant:165:in `new'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.6/bin/vagrant:165:in`<main>'
C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/fileutils.rb:1444:in `rmdir': Directory not empty @ dir_s_rmdir - C:/Users/RCGre/AppData/Local/Temp/vagrant-fs-case-sensitive20161026-1680-zbnngf (Errno::ENOTEMPTY)
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/fileutils.rb:1444:in`block in remove_dir1'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/fileutils.rb:1458:in `platform_support'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/fileutils.rb:1443:in`remove_dir1'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/fileutils.rb:1436:in `remove'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/fileutils.rb:778:in`block in remove_entry'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/fileutils.rb:1493:in `ensure in postorder_traverse'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/fileutils.rb:1493:in`postorder_traverse'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/fileutils.rb:776:in `remove_entry'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/tmpdir.rb:94:in`mktmpdir'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/util/platform.rb:139:in `fs_case_sensitive?'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/util/platform.rb:157:in`fs_real_path'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/environment.rb:121:in `initialize'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.6/bin/vagrant:165:in`new'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.6/bin/vagrant:165:in `<main>'
Some plugins had to be installed, please re-run your command

real    0m11.355s
user    0m0.000s
sys     0m0.031s
*\* Running vagrant up again after plugin install **
C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/fileutils.rb:1444:in `rmdir': Directory not empty @ dir_s_rmdir - C:/Users/RCGre/AppData/Local/Temp/vagrant-fs-case-sensitive20161026-10936-m8d89l (Errno::ENOTEMPTY)
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/fileutils.rb:1444:in`block in remove_dir1'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/fileutils.rb:1458:in `platform_support'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/fileutils.rb:1443:in`remove_dir1'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/fileutils.rb:1436:in `remove'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/fileutils.rb:778:in`block in remove_entry'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/fileutils.rb:1493:in `ensure in postorder_traverse'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/fileutils.rb:1493:in`postorder_traverse'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/fileutils.rb:776:in `remove_entry'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/tmpdir.rb:94:in`mktmpdir'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/util/platform.rb:139:in `fs_case_sensitive?'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/util/platform.rb:157:in`fs_real_path'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/environment.rb:121:in `initialize'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.6/bin/vagrant:165:in`new'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.6/bin/vagrant:165:in `<main>'

real    0m1.804s
user    0m0.000s
sys     0m0.015s
*\* Vagrant failed to bring the VM image up, look at errors above for clues **
*\* If this continues get help here: https://github.com/lordkator/ZonamaDev/issues **

Stopping, clearly at Vagrant failed to bring the VM image up
Anyone got a clue on how to clear this up?

Just to be clear, I'm pretty new to programming/code, so any help is appreciated. I don't know if this issue is new, but I feel it's best to bring it up eitherway, could just be a ruby error.

**Comment by TrueLokitus** [comment]
Managed to move around this issue by setting up a Virtual Box running Debian 8 following this thread https://github.com/lordkator/ZonamaDev/wiki/Standalone-Server-Notes 
So far so good, I'll post any issues in a new thread, apologies for not doing this sooner. However, if someone happens to find a solution to the original issue, then I am all ears :D

**Comment by TrueLokitus** [comment]
After looking through my options, I've found the solution to my original issue. It turns out, the plugins that are for vagrant were not installed or at least that process was skipped. So I had to manually install the vagrant-vbguest plugin, vagrant-reload plugin and vagrant-triggers. Then it would install virtual box after running the ./setup.sh command. This is the current progress to my solution to my original issue so then anyone who doesn't known how to fix it, can do so through this. Updates will come if any other errors occure.

**Comment by TrueLokitus** [comment]
So, after working through the original process, I keep on getting a particular error when trying to transfer the .tre files from the host to the guest in virtual box.

** Checking to make sure your guest is up...
** Getting ssh configuration...
C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/fileutils.rb:1444:in `rmdir': Directory not empty @ dir_s_rmdir - C:/Users/RCGre/AppData/Local/Temp/vagrant-fs-case-sensitive20161027-9544-m1qup5 (Errno::ENOTEMPTY)
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/fileutils.rb:1444:in `block in remove_dir1'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/fileutils.rb:1458:in `platform_support'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/fileutils.rb:1443:in `remove_dir1'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/fileutils.rb:1436:in `remove'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/fileutils.rb:778:in `block in remove_entry'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/fileutils.rb:1493:in `ensure in postorder_traverse'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/fileutils.rb:1493:in `postorder_traverse'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/fileutils.rb:776:in `remove_entry'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/tmpdir.rb:94:in `mktmpdir'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/util/platform.rb:139:in `fs_case_sensitive?'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/util/platform.rb:157:in `fs_real_path'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/environment.rb:121:in `initialize'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.6/bin/vagrant:165:in `new'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.6/bin/vagrant:165:in `<main>'
#####################################################################
# ERROR WHILE PROCESSING : Failed to get ssh config, GET HELP! (11) #
#####################################################################

Just to clarify, I have the most up to date version of Git, Vagrant and VirtualBox, so I assume it cannot be an error with those, I did uninstall Vagrant and reinstall it, but that made no difference. I went through the original process of install for the VM, but each time when it comes to moving the .tre files over to the VirtualBox VM, it fails due to not being able to retrieve the SSH config, which I know is there. I am running them all in adminstrator mode just so there are no blocks that way, but to no avail. Please, someone let me know if there is a way to fix this error.

**Comment by Farelli** [comment]
Hey TrueLokitus, sorry you're having all this trouble.

To clarify: you're using Windows as your host operating system here, correct?

Off-hand I remember a problem with ruby 2.2 and needing to upgrade to 2.3 for things to work correctly, so that might be the solution here.

If you can get on IRC, please connect to server irc.swgemu.com:6667 and then /join #emuyoda channel. There's usually at least one of us on there and we are more alerted to questions when you're in the middle of it.

I've pasted this link in there and we should have an answer for you soon.

**Comment by TrueLokitus** [comment]
Yes, Windows is my host operating system. I'll make sure to update ruby to 2.3 and get back to you or anyone else through IRC if anymore issues crop up. Thanks you for your help :)

**Comment by karlbunch** [comment]
Yea this looks like a ruby issue, I'm closing for now, sorry I was away didn't have a chance to jump in.
