### ISSUE TITLE
Improve TRE import process

### ISSUE THREAD

**Issue by karlbunch** [lordkator/ZonamaDev#19]
SCP from windows

Verify missing files

Check BEFORE boot

Nagg them via notices

**Comment by Scurby** [comment]
Same as #25 ?

-Host file sharing (Preferred)
-cloud drive (DropBox, etc.)
-Removable drive (USB, CD)
-Enable copy/paste to/from Host machine

**Comment by karlbunch** [comment]
Duplicate of #25
