### ISSUE TITLE
Unsupported version of virtualbox (5.1.10r112026), please upgrade to 5.0.12 or higher

### ISSUE THREAD

**Issue by nickwill86** [lordkator/ZonamaDev#190]
"Unsupported version of virtualbox (5.1.10r112026), please upgrade to 5.0.12 or higher"

I am trying to install the dev enviroment like I normally do, but this time ive encountered this error while inputting:

"curl -L http://downloads.lordkator.com/bootstrap.sh | bash"

(i tried posting this earlier but for some reason it did not get through)

**Comment by lordkator** [comment]
For future reference, if you get stuck with this you can manually kick the process back off:

```bash
cd ~/ZonamaDev/fasttrack
./setup.sh
````
