### ISSUE TITLE
Handle build file deletions from repo

### ISSUE THREAD

**Issue by karlbunch** [lordkator/ZonamaDev#191]
In an effort to clean up the repo we're starting to delete auto generated files from the repo.

ZD has some scripted parts that knew those files were in the repo and are now failing because they've gone away.

http://review.swgemu.com/#/c/5285/

http://pastebin.com/ZuURLA1c

**Comment by lasko2112** [comment]
http://pastebin.com/xaUgKt3i

This paste will last longer than the original above.

An just to confirm what was said on irc.
The image was a pre-existing image that was completely unaltered.

**Comment by Farelli** [comment]
Just submitted a pull request for this case.

**Comment by karlbunch** [comment]
Great work @Farelli thanks again for your help!
