### ISSUE TITLE
VBoxManage: error: Details: code NS_ERROR_FAILURE

### ISSUE THREAD

**Issue by cookshee** [lordkator/ZonamaDev#194]
Hi, 

I setup a Debian 8.4 fresh install under Hyper-V and install Vagrant and VirtualBox then run the curl script:
...
** Checking for VirtualBox **
** Virtualbox version 5.1.12r112440 **
** Checking for Vagrant **
** Vagrant version 1.9.1 **
...
==> default: Booting VM...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "6c26795b-2b41-4ef1-9d2a-88c87c5289b9", "--type", "gui"]

Stderr: VBoxManage: error: The virtual machine 'ZonamaDev-1482366269' has terminated unexpectedly during startup because of s                        ignal 6
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MachineWrap, interface IMachine

Can you help me out this error? 

Thank you so much!

Regards, 

Cook

**Comment by cookshee** [comment]
Yep the installed Os is Debian 8.4

Or I do it but it still fails:

root@xxxx:~# curl -L http://downloads.lordkator.com/bootstrap.sh | bash

  % Total    % Received % Xferd  Average Speed   Time    Time     Time
Current

                                 Dload  Upload   Total   Spent    Left
Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:--
--:--:--     0

100 10481  100 10481    0     0  14393      0 --:--:-- --:--:-- --:--:--
14393

** Checking for VirtualBox **

** Virtualbox version 5.1.12r112440 **

** Checking for Vagrant **

** Vagrant version 1.9.1 **

** ZDHOME=/root **

fatal: destination path 'ZonamaDev' already exists and is not an empty
directory.

Already up-to-date.

** Running in /root/ZonamaDev/fasttrack **

** Using default cores/ram **

vagrant up

Bringing machine 'default' up with 'virtualbox' provider...

==> default: Checking if box 'lordkator/swgemudev-deb-jessie' is up to
date...

Your VM has become "inaccessible." Unfortunately, this is a critical error

with VirtualBox that Vagrant can not cleanly recover from. Please open
VirtualBox

and clear out your inaccessible virtual machines or find a way to fix

them.



real    0m6.254s

user    0m4.488s

sys     0m0.472s

** Vagrant failed to bring the VM image up, look at errors above for clues
**

** If this continues get help here:
https://github.com/lordkator/ZonamaDev/issues **


Then I start from fresh:

root@xxxx:~# curl -L http://downloads.lordkator.com/bootstrap.sh | bash -s
destroy

  % Total    % Received % Xferd  Average Speed   Time    Time     Time
 Current

                                 Dload  Upload   Total   Spent    Left
 Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--
  0

100 10481  100 10481    0     0  17949      0 --:--:-- --:--:-- --:--:--
17949

##################################################################################

## WARNING THIS WILL REMOVE ALL ZonamaDev VM's AND REMOVE YOUR ZonamaDev
FOLDER ##

##################################################################################


Are you sure you want to destroy the old setup? Y

** Checking for ZonamaDev vagrant VM images...

Destroy VMid 0ff4c5c from /root/ZonamaDev/fasttrack

Your VM has become "inaccessible." Unfortunately, this is a critical error

with VirtualBox that Vagrant can not cleanly recover from. Please open
VirtualBox

and clear out your inaccessible virtual machines or find a way to fix

them.

** No ZonamaDev VM images where found **

** Removing any cached copies of base box **

Removing box 'lordkator/swgemudev-deb-jessie' (v1.1.0) with provider
'virtualbox'...

** Looking for the ZonamaDev host directory...

** Removing /root/ZonamaDev **

** Removed ZonamaDev host directory **

** Removing vagrant settings directory **

######################################

## ZonamaDev Host Environment Reset ##

######################################

** Checking for VirtualBox **

** Virtualbox version 5.1.12r112440 **

** Checking for Vagrant **

** Vagrant version 1.9.1 **

** ZDHOME=/root **

Cloning into 'ZonamaDev'...

remote: Counting objects: 4675, done.

remote: Compressing objects: 100% (5/5), done.

remote: Total 4675 (delta 0), reused 0 (delta 0), pack-reused 4670

Receiving objects: 100% (4675/4675), 17.39 MiB | 1.52 MiB/s, done.

Resolving deltas: 100% (2819/2819), done.

Checking connectivity... done.

** Running in /root/ZonamaDev/fasttrack **

** Using default cores/ram **

vagrant up

Installing the 'vagrant-vbguest' plugin. This can take a few minutes...

Fetching: micromachine-2.0.0.gem (100%)

Fetching: vagrant-vbguest-0.13.0.gem (100%)

Installed the plugin 'vagrant-vbguest (0.13.0)'!

Installing the 'vagrant-reload' plugin. This can take a few minutes...

Fetching: vagrant-reload-0.0.1.gem (100%)

Installed the plugin 'vagrant-reload (0.0.1)'!

Installing the 'vagrant-triggers' plugin. This can take a few minutes...

Fetching: bundler-1.13.6.gem (100%)

Fetching: vagrant-triggers-0.5.3.gem (100%)

Installed the plugin 'vagrant-triggers (0.5.3)'!

Some plugins had to be installed, please re-run your command


real    0m16.271s

user    0m7.720s

sys     0m0.416s

** Running vagrant up again after plugin install **

Bringing machine 'default' up with 'virtualbox' provider...

==> default: Box 'lordkator/swgemudev-deb-jessie' could not be found.
Attempting to find and install...

    default: Box Provider: virtualbox

    default: Box Version: 1.1.0

==> default: Loading metadata for box 'lordkator/swgemudev-deb-jessie'

    default: URL: https://atlas.hashicorp.com/lordkator/swgemudev-deb-jessie

==> default: Adding box 'lordkator/swgemudev-deb-jessie' (v1.1.0) for
provider: virtualbox

    default: Downloading:
https://atlas.hashicorp.com/lordkator/boxes/swgemudev-deb-jessie/versions/1.1.0/providers/virtua
                             lbox.box

==> default: Successfully added box 'lordkator/swgemudev-deb-jessie'
(v1.1.0) for 'virtualbox'!

==> default: Importing base box 'lordkator/swgemudev-deb-jessie'...

==> default: Matching MAC address for NAT networking...

==> default: Checking if box 'lordkator/swgemudev-deb-jessie' is up to
date...

==> default: Setting the name of the VM: ZonamaDev-1482447427

==> default: Clearing any previously set network interfaces...

==> default: Preparing network interfaces based on configuration...

    default: Adapter 1: nat

==> default: Forwarding ports...

    default: 44480 (guest) => 44480 (host) (adapter 1)

    default: 44443 (guest) => 44443 (host) (adapter 1)

    default: 44455 (guest) => 44455 (host) (adapter 1)

    default: 44453 (guest) => 44453 (host) (adapter 1)

    default: 44462 (guest) => 44462 (host) (adapter 1)

    default: 44463 (guest) => 44463 (host) (adapter 1)

    default: 22 (guest) => 2222 (host) (adapter 1)

==> default: Running 'pre-boot' VM customizations...

==> default: Booting VM...

There was an error while executing `VBoxManage`, a CLI used by Vagrant

for controlling VirtualBox. The command and stderr is shown below.


Command: ["startvm", "a86bdaa4-80e1-4d2d-b4be-3b9225b80251", "--type",
"gui"]


Stderr: VBoxManage: error: The virtual machine 'ZonamaDev-1482447427' has
terminated unexpectedly during startup because of signal 6

VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component
MachineWrap, interface IMachine



real    31m38.180s

user    0m55.564s

sys     0m33.164s

** Vagrant failed to bring the VM image up, look at errors above for clues
**

Same error no success.

Can you help me out of this?

Thank you!

Regards,

Cook

**Comment by Farelli** [comment]
We're looking into this. Thanks for the code post, that'll really help us narrow it down.

**Comment by karlbunch** [comment]
Why are you launching debian inside a hyper-v and then trying to do a linux install of ZD?

Just launch ZD from gitbash in windows?

https://github.com/lordkator/ZonamaDev#windows-host

Most likely you are launching a deb in hyper-v and then trying to do virtualbox in that and running into common issues of trying to run virtualization inside virtualization.  There is zero advantage to crating the Hyper-V debian instance and then creating another instance inside that one.

**Comment by karlbunch** [comment]
Also @cookshee if you want interactive help please join the #emuyoda channel in IRC and ask questions there, most of the time someone is hanging around who can help and each day I check for messages there etc.

**Comment by cookshee** [comment]
Hi,

Yep it's insane, but I just follow the RECOMMENDED tutorial. :)

No install the standalone (not recommended) server inder debian 8.4 and
finaly got a first boot success. Can you send me the irc server name too to
connect you?

Thank you for your support and merry XMas! :)

Cook

**Comment by karlbunch** [comment]
To be clear the recommended if you're on windows is to use virtualbox not hyper-v and a debian box.

Help with IRC can be found on the forums, http://www.swgemu.com/forums/content.php?r=154-Configuring-mIRC

**Comment by Farelli** [comment]
irc.swgemu.com:6667/%23emuyoda
