### ISSUE TITLE
Desktop HTML doc for FAQ and How-To's

### ISSUE THREAD

**Issue by karlbunch** [lordkator/ZonamaDev#22]

**Comment by Scurby** [comment]
# FAQ

### How do I enable the admin commands?

To enable these features in the client you will need to edit the user.cfg file in the c:\SWGEMU folder to add these 4 liness:
>[ClientGame]
>0fd345d9 = true
>[ClientUserInterface]
>debugExamine=1

If the user.cfg file doesn’t exist, simply copy swgemu.cfg and rename it as user.cfg. Then, replace the contents of the new user.cfg with the contents of the table above.

You might also need to add a line in swgemu.cfg to tell the client to use the new user.cfg file:

>.include "swgemu_login.cfg"
>.include "swgemu_live.cfg"
>.include "swgemu_preload.cfg"
>.include "options.cfg"
>.include "user.cfg" <-- THIS LINE MIGHT BE MISSING or Commented out

Once the config files are done, totally shut down your client (if running) and restart it.

### How do I create an admin account?

In MySQL Workbench, go to Schemata--->swgemu--->accounts--->go to admin_level---> change 0 to 15--->Apply change--->Execute--->Then do build config again.

### How do I shutdown the server?

In the active terminal enter:
>save (Wait for save to complete)
>exit
>Cntl-c

### How do i start the server?

Open a terminal and enter:
>cd ~/MMOCoreOrb/bin
>./core3

### How do I sign in to Gerrit? I keep getting a server error when I try to login?

### How do I connect to my dev env server with Launchpad?

### How do I find the server IP address?

### How do I enable other planets? 

### How do I edit config.lua?

**Comment by Scurby** [comment]
See sample HTML doc for review. 
Suggest FAQ.md

**Comment by karlbunch** [comment]
I hope we can automate a lot of these away and just point them to a menu.

**Comment by karlbunch** [comment]
All in yoda now.
