### ISSUE TITLE
SOLVE: How do I copy the .tre files to the VM environment?

### ISSUE THREAD

**Issue by karlbunch** [lordkator/ZonamaDev#25]
http://www.swgemu.com/forums/showthread.php?t=85624&p=672706&viewfull=1#post672706

**Comment by Scurby** [comment]
-cloud drive (DropBox)
-flash drive (USB)
-Host file sharing

**Comment by karlbunch** [comment]
If they're using Git Bash we can just scp the files like under OSX!

It'll be easy to script! :+1:

**Comment by Scurby** [comment]
Perfect!
