### ISSUE TITLE
SOLVE: How do I create an admin account?

### ISSUE THREAD

**Issue by karlbunch** [lordkator/ZonamaDev#30]
http://www.swgemu.com/forums/showthread.php?t=85624&p=833604&viewfull=1#post833604

**Comment by Scurby** [comment]
Set acct ID=1  level to 15

**Comment by karlbunch** [comment]
I plan to script this, we can make a panel with common commands.

**Comment by karlbunch** [comment]
Yoda makes this easy.

http://127.0.0.1:44480/
