### ISSUE TITLE
SOLVE: How do I enable the admin commands?

### ISSUE THREAD

**Issue by karlbunch** [lordkator/ZonamaDev#31]
http://www.swgemu.com/forums/showthread.php?t=85624&p=1247644&viewfull=1#post1247644

**Comment by Scurby** [comment]
# Enabling Admin Commands and Debug Examine in Your Client

To enable these features in the client you will need to edit the user.cfg file in the c:\SWGEMU			folder to add these 4 liness:

>[ClientGame]
>0fd345d9 = true
>[ClientUserInterface]
>debugExamine=1

If the user.cfg file doesn’t exist, simply copy swgemu.cfg and rename it as user.cfg. Then, replace the contents of the new user.cfg with the contents of the table above.

You might also need to add a line in swgemu.cfg to tell the client to use the new user.cfg file:

>.include "swgemu_login.cfg"
>.include "swgemu_live.cfg"
>.include "swgemu_preload.cfg"
>.include "options.cfg"
>.include "user.cfg"      <-- THIS LINE MIGHT BE MISSING or Commented out

Once the config files are done, totally shut down your client (if running) and restart it.

**Comment by karlbunch** [comment]
We can script this!

**Comment by Scurby** [comment]
Really? This is the client in the windows host... we can do that from the vm guest?

**Comment by karlbunch** [comment]
Use the source luke.. If they have Git Bash we can script it on their side.  At least on the first machine they start from we can help them make sure that one is working.

**Comment by karlbunch** [comment]
Yoda documents this.
