### ISSUE TITLE
SOLVE: How do I shutdown the server?

### ISSUE THREAD

**Issue by karlbunch** [lordkator/ZonamaDev#33]
http://www.swgemu.com/forums/showthread.php?t=85624&p=780413&viewfull=1#post780413

**Comment by Scurby** [comment]
### Server Shutdown

In the active terminal enter
1. save
  * This can take some time. Wait for the save to finish. You will notice 'IDLE'  on the terminal.
2. exit
3. Cntl-c

**Comment by karlbunch** [comment]
Better under screen we can send it commands!

man screen

See the -X option.. I used something like this to script my minecraft servers so the wife could send console commands etc. and output ends up in screenlog..

So we might have a panel open to send commands and log them etc.

**Comment by Scurby** [comment]
I see it...  We may need more than one panel. ;-)

- Start up
  - Config
  - Builds
    - build
    - config build
- Debug (default)
  - gdb (on)
  - valgrind (off)
  - Prelocks (off)
  - Unit tests (off)
  - More
- Git
  - Clone
  - Pull (Stash and Re-apply)
  - Push
  - New branch
  - More
- Links here?
- Vagrant
  - up
  - destroy
  - snapshot
  - more
- Shutdown
  - Immediate
  - Safe Exit
  - Timed Safe Exit

**Comment by karlbunch** [comment]
Click the button!

or from terminal do:

swgemu stop
