### ISSUE TITLE
Include links

### ISSUE THREAD

**Issue by Scurby** [lordkator/ZonamaDev#35]
# Links
### Main

[SWGEmu Forums](http://www.swgemu.com)
[Mantis Bug Tracker](http://www.swgemu.com/bugs)
[Gerrit Code Review](http://review.swgemu.com/#/q/status:open,n,z)
[Mod The Galaxy](http://www.modthegalaxy.com)
[SWGEmu Server Stats](https://stats.revelationonline.net/)
### Dev

[SWGEmu-Community-Contributions](https://github.com/SWGEmu-Community-Contributions/DevEnv)
[Scrapbookv51](http://www.swgemu.com/archive/scrapbookv51/tree/frame.html)
[ANH Wiki](http://wiki.swganh.org/index.php/Main_Page)
[Convo Editor](http://www.bluree.net/convos/)
[String Search Tool](http://swg.bass-speaker.com/strings.php)
[Netyoda's Creature Database](http://www.netyoda.co.uk/swg/mobs/critters.php?srt=creature&d=d)
[Previous FastTrack VM Image](http://www.swgemu.com/forums/showthread.php?t=85624)
### Fun

[Commit Logs From Last Night](http://www.commitlogsfromlastnight.com/)
[A Girl and her Wookiee](http://www.hurm.com/agahw/archives/)
[Greep](http://greepnewbish.com/)
[Star Wars Weather Forecast](http://www.tomscott.com/weather/starwars/)

**Comment by karlbunch** [comment]
All in yoda now.
