### ISSUE TITLE
make sure vagrant snapshots behave well

### ISSUE THREAD

**Issue by karlbunch** [lordkator/ZonamaDev#38]
vagrant restore runs provisioning, need to verify it won't break stuff.

Document vagrant snapshot usage so people can make their lives easier.

Debate, should we make a fresh snapshot just after gerrit registration success or clone?

**Comment by Scurby** [comment]
Can we do both? And give the option on restore?

After gerrit registartion suggests the user feels the need to re-clone to start with a fresh SWGEmu code base.

After clone suggests the user wants to revert to a previous version of their branch of the code base. I offer that git branching serves this purpose better. On that note.. few of our users take advantage of git branching so, this may be an easier solution for them.

**Comment by karlbunch** [comment]
I'm thinking the whole box gets snapshot so if they mess up their SYSTEM they can restore.  We of course should encourage and teach using git to make life better for them on the code side of things.

**Comment by karlbunch** [comment]
Doesn't seem relevant anymore.
