### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by Scurby** [lordkator/ZonamaDev#39]
cd build/unix && make clean
make[1]: Entering directory '/home/vagrant/workspace/Core3/MMOCoreORB/build/unix'
CDPATH="${ZSH_VERSION+.}:" && cd ../.. && /bin/bash /home/swgemu/workspace/Core3/MMOCoreORB/build/unix/config/missing --run aclocal-1.11 
/bin/bash: /home/swgemu/workspace/Core3/MMOCoreORB/build/unix/config/missing: No such file or directory
Makefile:295: recipe for target '../../aclocal.m4' failed
make[1]: *** [../../aclocal.m4] Error 127
make[1]: Leaving directory '/home/vagrant/workspace/Core3/MMOCoreORB/build/unix'
Makefile:85: recipe for target 'clean' failed
make: *** [clean] Error 2
vagrant@swgemudev:~/workspace/MMOCoreORB$

**Comment by karlbunch** [comment]
Did you make config?  

The steps are only complete to the clone, then you have to do:

cd ~/workspace/Core3/MMOCoreORB

make config ; make clean ; time make -k build

**Comment by karlbunch** [comment]
Just verified from:

vagrant up
(register with Gerrit -> Clone)
(Open terminal)
````
cd ~/workspace/Core3/MMOCoreORB
make config ; make clean ; time make -k build
aclocal
automake --add-missing
configure.ac:13: installing 'build/unix/config/compile'
configure.ac:2: installing 'build/unix/config/config.guess'
configure.ac:2: installing 'build/unix/config/config.sub'
configure.ac:7: installing 'build/unix/config/install-sh'
configure.ac:7: installing 'build/unix/config/missing'
..[truncated]..
cp build/unix/src/client/core3* bin
cp build/unix/src/core3* bin
#cd bin/conf && svnversion > rev.txt
cd bin/conf && git log --pretty=format:'%h was %an, %ar, message: %s' -10 > rev.txt
rm build/unix/src/core3
#done

real    20m58.082s
user    37m31.904s
sys     3m8.728s
````

NOTE: Default is 2 cores, 2 gig, we need to fix that, I can get this down to 5 mins on my laptop! See #41
