### ISSUE TITLE
Panel Main

### ISSUE THREAD

**Issue by Scurby** [lordkator/ZonamaDev#40]
Issues included #22 #24 #26 #27 #28 #30 #31 #32 #33 #35 #36 
- Start up
  - Config
    - ~~Edit config~~
    - ~~Saved configs~~
  - ~~Builds~~
    - ~~build~~
    - ~~config build~~
    - ~~run no build~~
- IP
  - ~~Current (running) Server IP~~
  - ~~Update IP table~~
  - ~~How to connect client.~~
- Debug (default)
  - ~~gdb~~ (on)
  - valgrind (off)
  - Prelocks (off)
  - Unit tests (off)
  - More
- Git
  - ~~Clone~~
  - ~~Pull (Stash and Re-apply)~~
  - Push
  - New branch
  - More?
- Links here?
- Vagrant
  - ~~Export/Import user settings/extras~~
  - up
  - destroy
  - snapshot
  - more
- Shutdown
  - ~~Immediate~~
  - Force SegFault
  - ~~Safe Exit~~
  - ~~Timed Safe Exit~~

**Comment by karlbunch** [comment]
I debate on us doing a web page for these.. Could have a small micro server running on the box (openresty being my favorite) and some LUA API code on it to do much of these things etc.

**Comment by karlbunch** [comment]
Some of these are in basebox 1.0.0 now.

**Comment by karlbunch** [comment]
Yoda
