### ISSUE TITLE
Count number of host cores and suggest more cpu's for guest

### ISSUE THREAD

**Issue by karlbunch** [lordkator/ZonamaDev#41]
On Windows: wmic cpu get NumberOfCores  or $NUMBER_OF_PROCESSORS

On OSX: sysctl -n hw.ncpu

On Linuc: nproc

Git, make and several other steps can really use a lot of cores.  Even including hyper threads helps with compile (e.g. 1 Proc, 4 Cores with 8 Hyper Threads, v.cpus=8 works well)

**Comment by karlbunch** [comment]
NOTE: We may want to WARN them also when they allocate too much like 2Gb on a 3Gb laptop.

Per @Scurby :smiling_imp:

**Comment by lordkator** [comment]
Windows ram: 

```
 wmic memorychip get capacity|awk 'NR > 1 {x = x + $1 } END { print x / 1024 / 1024 }'
````

**Comment by lordkator** [comment]
````
$ wmic memorychip get capacity|awk 'NR > 1 {x = x + $1 } END { print x / 1024 / 1024 }'
16384
````

**Comment by karlbunch** [comment]
Ram on OSX:

```
$ sysctl -n hw.memsize|awk '{ print $1 / 1024 / 1024 }'
12288
```

Cores on OSX:
````
$ sysctl -n hw.ncpu
16
````
