### ISSUE TITLE
User debug collection

### ISSUE THREAD

**Issue by karlbunch** [lordkator/ZonamaDev#44]
Need a simple way for someone to report a dev environment bug and send us logs plus output of things like:

````
top -Hbn 1
df - h
uname -a
````

Maybe a gist post or some other process..

**Comment by Scurby** [comment]
Correction:
top Hbn 1
df -h
uname -a

**Comment by karlbunch** [comment]
More like:

````
(top -Hbn 1;df -h;uname -a) > ~/Desktop/devenv.txt
````

**Comment by Scurby** [comment]
should we append the doc?

**Comment by karlbunch** [comment]
Maybe:

````
sudo gem install gist
(top -Hbn 1;df -h;uname -a)|gist
````
Example output: https://gist.github.com/c4ef828923e903ef19db
