### ISSUE TITLE
tre.sh

### ISSUE THREAD

**Issue by Scurby** [lordkator/ZonamaDev#52]
When using ./tre.sh in Host I get this error.

>$./tre.sh
> **TRE File Copy
>./tre.sh: line 111: tty: command not found
>
>** Ok we found your files in /c/SWGEmu, we will now try and copy them to your guest...
>
>./tre.sh: line 31: mktemp: command not found
>** Checking to make sure your guest is up...
>** Getting ssh configuration...
>./tre.sh: line 38: 1: ambiguous redirect
>
>**ERROR WHILE PROCESSING : Failed to get ssh config, GET HELP! (11)

**Comment by karlbunch** [comment]
Need newer version like 4.3.2, I added some tests to check for needed commands and complain if they're missing.
