### ISSUE TITLE
Offline tools.

### ISSUE THREAD

**Issue by Scurby** [lordkator/ZonamaDev#56]
Downloads for local copies of:
- scrapbookv51
- soe archived forums
- google docs (Current pub checklist)
- dropbox
- convo editor
- string searcher

**Comment by Scurby** [comment]
[Scrapbook](https://www.dropbox.com/s/23ufrsi7hffix6k/Scrapbook.zip?dl=0)
[String tool](https://www.dropbox.com/s/wrlnb4jt53zfmmt/StfSearcher-1.0.3.zip?dl=0)

**Comment by karlbunch** [comment]
Hey @Scurby the scrapbook is 1.5 GB uncompressed, are you sure you want this in by default?

The string tool is Java client, going the wrong direction for headless, I know there used to be a web based version, do we have the source to that?  Or should I consider making one?

**Comment by Scurby** [comment]
Web Based String Tool
http://swg.bass-speaker.com/strings.php

**Comment by karlbunch** [comment]
Moved to https://github.com/Zonama/ZonamaDev/projects/2
