### ISSUE TITLE
Cannot download virtualbox image from atlas.hashicorp (404)

### ISSUE THREAD

**Issue by gregslomin** [lordkator/ZonamaDev#58]
Trying to run the script results in the following after creating an atlas account:

""The box 'lordkator/swgemudev-deb-jessie' could not be found or could not be accessed in the remote catalog."

Looking at the page: https://atlas.hashicorp.com/lordkator it says "There aren't any boxes to show."

I'm unsure if this is an account permissions error or maybe perhaps the files are gone at the moment?

Here is a log of my full run - https://gist.github.com/gregslomin/5d31b3445e5ee7090e7d

**Comment by karlbunch** [comment]
Get @gregslomin can you setup an atlas account and give me your username.

**Comment by karlbunch** [comment]
To be clear do this: https://atlas.hashicorp.com/account/new

No need for anything more than a valid username and then I can add you to the box.

We're still in alpha so the boxes are locked down.

**Comment by gregslomin** [comment]
The username on the Atlas account I am using is "Reoze". I appreciate the help.

**Comment by karlbunch** [comment]
DONE

Try again!

:smile:
