### ISSUE TITLE
SCP fails to copy TRE files

### ISSUE THREAD

**Issue by gregslomin** [lordkator/ZonamaDev#60]
After entering the correct directory for the StarWarsGalaxies installation and telling the script to search for the tre files I was presented with the following message.

 (  ** Ok we found your files in , we will now try and copy them to your guest... )

However after the VM launches the SCP copy fails with a file not found error. It appears the path is not being prepended properly (/*.tre: No such file or directory  )

I'm unsure if it's related but I did input the wrong directory the first time "Program Files" instead of "Program Files (x86)". It could be possible this is what caused the error. 

I made a gist of the full log of the "TRE File Copy" section of my script output here: 
https://gist.github.com/gregslomin/e550a2afa1063c309b14

**Comment by karlbunch** [comment]
Hey @gregslomin test this again and re-open if it's still broken with latest.
