### ISSUE TITLE
Suggestion: Limit git clone depth

### ISSUE THREAD

**Issue by gregslomin** [lordkator/ZonamaDev#61]
Currently the scripts on the guest machine appear to clone each repository with their full depth. By limiting the depth of the git clone it would make it much more friendly for those without extremely fast connections, as well as speed the process up by quite a few orders of magnitude over a full clone.

For comparison, on the VM the following command only took 25 seconds to execute and only transferred 37.5MB of data in total.   git clone https://github.com/TheAnswer/Core3.git --depth 5  

Whereas a full clone, without any depth limiting took over 4 minutes (the majority of which it was "counting" objects) and transferred 225MB in total. This could dramatically speed things up for people who have sub-par connections. 

The downside to limiting the clone depth is that a "git log" will only show last "x" number of entries before the history ends, depending on how far the depth is limited. This generally is not an issue as people can either clone the full repository if they wish or view the history on github, or gerrit.

**Comment by karlbunch** [comment]
We're debating on having the repo cloned in the base box and just doing pull on load of the fasttrack.
