### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by Scurby** [lordkator/ZonamaDev#65]
Add to documentation? 

HOW TO: Run Unit Tests
SWGEmu has a growing number of unit tests that validate functionality automatically.

Jenkins runs all unit tests as part of the verification build. A commit that breaks a unit test will not be merged into the baseline.

Before pushing changes, you should always run the unit tests in your development environment.

Run All Unit Tests

> cd /home/!username/workspace/MMOCoreORB/bin
> ./core3 runUnitTests

Run Specific Unit Tests

>  cd /home/!username/workspace/MMOCoreORB/bin
> ./core3 runUnitTests --gtest_filter=<FILTERSTRING>

where <FILTERSTRING> is the name of a specific test as defined in the TEST_F call. Wildcards may be used. For example --gtest_filter=LuaMobile\* runs all tests in LuaMobileTest.cpp

**Comment by Farelli** [comment]
Working on this now.

**Comment by karlbunch** [comment]
Done
