### ISSUE TITLE
File associations in Eclipse

### ISSUE THREAD

**Issue by Scurby** [lordkator/ZonamaDev#66]
Window -> Preferences -> General -> Editors -> File associations. Add

*.idl

and others

**Comment by karlbunch** [comment]
Hey @Scurby what are all of them we need to add so I can put them in the base box setup.

I'd like to get this in Milestone 1.1.0

**Comment by Scurby** [comment]
.lua .txt .h .cpp.

**Comment by karlbunch** [comment]
@Scurby I Did by hand on 1.1 box, please verify let me know if anything is missing then re-open this issue.
