### ISSUE TITLE
Slowbrain // NEWB  // Needs Help.

### ISSUE THREAD

**Issue by zycor** [lordkator/ZonamaDev#72]
I have my own repository with the MMOCoreORB and all the jazz inside. I read the read me, I typed in my git info, it didn't load it.

All I'm trying to do is make a simple dev environment using this so I can edit mobs.

**Comment by zycor** [comment]
gETTING these errors, with the engine.

https://gyazo.com/1d184e8a06c7107fb622b52a69301762

**Comment by zycor** [comment]
https://gyazo.com/2b39976d93d03f2f66b691504ea5d93b

**Comment by karlbunch** [comment]
If you are not using the Gerrit repo and following the directions we're not able to support you.

On your host do:

cd ZonamaDev/fasttrack
vagrant destroy
./setup.sh

Follow the directions exactly, all the way to the build.

Once you have a clean local build if you want to switch git repos fine, but we are not here to help you code or fix your broken repo. :smile_cat:

**Comment by zycor** [comment]
ty
