### ISSUE TITLE
Shuttles not working

### ISSUE THREAD

**Issue by ShiranJacq** [lordkator/ZonamaDev#85]
Hello Everyone,
Impossible to use ShuttlePort or Starports i always have a message "Shuttle destroyed by terrorist" and in the log of Core3 i have  : "missing a shuttle object"

Someone already did have this problem ?

**Comment by karlbunch** [comment]
is it every shuttleport or just specific ones?  I've not seen this error in ages, it was actually an error I added way back when I was working on shuttles, would be helpful if you can get specific about where (i.e. naboo Spaceport, etc.) and maybe post your core3 log to a gist?

I'd stop server with your toon sitting next to a shuttle, then start the server and try to shuttle a couple times then do:

````
sudo gem install gist
cd cd ~/workspace/Core3/MMOCoreORB/bin/log
tac core3.log | gist
````

Please share the gist url here.

**Comment by karlbunch** [comment]
Closing since we've not heard back.
